apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: exam
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
