apiVersion: v1
kind: LimitRange
metadata:
  name: exam-limits
  namespace: exam
spec:
  limits:
    - default: # limites par défaut
        cpu: "500m" # 500 milliCPU = 0.5 CPU
        memory: "512Mi"
      defaultRequest: # requêtes par défaut
        cpu: "200m" # 200 milliCPU = 0.2 CPU
        memory: "256Mi"
      max: # limites maximales
        cpu: "1" # 1 CPU
        memory: "1Gi"
      min: # limites minimales
        cpu: "100m" # 100 milliCPU = 0.1 CPU
        memory: "128Mi"
      type: Container
